### ISSUE TITLE
[Bug] Unable to change game settings after loading Mod

### ISSUE THREAD

**Issue by Dss0** [iw4x/iw4x-rawfiles#1]
Smol Bug:

1. Load any mod
2. Go to custom games and click "change game settings"

Expected Result: The game settings menu opens
Result: Nothing happens

Workaround: Do /reloadmenus, that'll fix it until you load a different mod.

Not sure if this is related to menu files or the menu load code.

**Comment by diamante0018** [comment]
Please show a video, I have no idea what this is about as I did a few tests and found no apparent issues.

**Comment by Dss0** [comment]
Can't reproduce it anymore with the latest version of iw4x 🤷
