### ISSUE TITLE
IW3 killhouse and all iw3 spetsnaz models 

### ISSUE THREAD

**Issue by The-Red-Menace** [iw4x/iw4x-rawfiles#20]
the iw3 spetsnaz models for killhouse and all other iw3 maps that are "Urban" use the woodland version of their models
ex the sniper class should not be a ghillie suit
Below are the models that each class isnt using on urban spetsnaz maps:
Sniper
![20240124084123_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/a0124c87-2f23-4a8a-a4f9-58d173c980bb)
Assault
![20240124084258_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/4c72b08b-0a1f-48c8-850c-323f4808c513)
SMG
![20240124084323_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/a4b714db-0f01-4504-a66b-e6101a6bff32)
LMG
![20240124084348_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/f0414d8f-04d9-4366-a1cb-58cda581bc50)
Shotgun(would assume this is unused on purpose for each faction since shotguns are secondary's on iw4x)
![20240124084429_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/d2b3820a-3eb8-4cd9-932b-7c97e53250db)

**Comment by Rackover** [comment]
![image](https://github.com/iw4x/iw4x-rawfiles/assets/33836535/bdf8e195-aeac-4069-a05c-f1aace1f6488)

on it
