### ISSUE TITLE
IW3 factions and models do not line up with weapon class

### ISSUE THREAD

**Issue by The-Red-Menace** [iw4x/iw4x-rawfiles#21]
For iw3 most of the factions are messed up for the character models(the pictures is how they should look for each weapon class)
ex:
Left is weapon class used and right is the model used
-ASSAULT class=SMG model
-SMG class=LMG model
-LMG class=Shotgun model
-Sniper class=Ghillie suit(this is for all factions it just uses the rangers/spetsnaz when it should be each unique models)
-Shotgun class(I guess it was unused since they are secondary's but ill put them down in case)
assault model seems to be missing totally
riot shield seems to use the mw2 models since it doesn't have shields in iw3
this is how its been for all of the factions
-(Also for some reason the default assault class uses the smg model but also if you have another assault class it uses the actual assault character model for some reason that said goes for all factions like mentioned)
-the smg/lmg models for opfor were flipped in mwr but that's up to you I prefer the lmg from mwr with the RPG backpack to make more sense
-the sas smg/shotgun were flipped in mwr too

(the urban version of spetsnaz is completely gone too when it should be on maps like killhouse)
Below are what the factions should look like:
Marines:

Assault
![20240124085204_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/21b3ac3a-9057-4a46-bfcb-a5dc848fd48d)
SMG
![20240124085234_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/69d9a4d9-24a7-4ff7-93e5-031040776115)
LMG
![20240124085324_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/105d2d69-4538-4316-b150-efcb0d91da8c)
Shotgun
![20240124085445_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/13612382-5333-46e1-ba67-ce9bd991ffac)
Sniper
![20240124085522_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/a091dfba-0bd2-4c43-8ca6-440ae7cfe257)

Spetsnaz(Woodland)

Assault
![20240124084258_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/3f21aea3-dc54-49c2-a491-58a046d25264)
SMG
![20240124084323_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/5e1d3f89-904d-4c21-a3b6-e3da7bb992d4)
LMG
![20240124084348_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/c857d4c5-ae4b-420d-be30-fd40888c3449)
Shotgun
![20240124084429_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/d250f7d8-c6ff-4672-81ab-a65426124c11)
Sniper
![20240124084123_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/8d777c58-4624-4c62-bbbc-658caf5a6d81)

Opfor:

Assault
![20240124090132_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/ef3660ed-a3d8-4fd2-b8f2-305f836e9939)
SMG
![20240124090218_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/f783d113-9a88-47b7-b854-0ec6fdc85ac1)
LMG
![20240124090405_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/a03f7d8e-d108-4527-943e-c840fbac1be2)
Shotgun
![20240124090527_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/598f31b6-26db-49b7-839b-b2009017d9eb)
Sniper
![20240124090608_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/f5ee7db2-8c29-4c71-8bc7-6a8e0e83fb8f)

Spetsnaz(Urban)

Assault
![20240124090933_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/47e4e945-4988-4a35-abed-1a69ea82dd2f)
SMG
![20240124090959_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/5177a2ec-468e-49de-93b1-eb0b5f7ee771)
LMG
![20240124091058_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/679fa041-4a94-41f7-a081-9b9b11e94b78)
Shotgun
![20240124091136_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/a7d84e8f-172d-4081-ba20-8d6a0684a344)
Sniper
![20240124091216_1](https://github.com/iw4x/iw4x-rawfiles/assets/157612628/765d79b4-7077-470d-a623-0927a86192e6)

There isn't room for more pictures so ill just post a second issue with the last 2 sets of pictures

**Comment by Rackover** [comment]
Thanks a bunch for the detailed bug report, description and screenshots, this helped me a ton while fixing this :)

Please reopen if I didn't get everything right, I'll try to get back to it
