### ISSUE TITLE
Wrong (?) Task Force 141 icon in all maps

### ISSUE THREAD

**Issue by AkimboTH** [iw4x/iw4x-rawfiles#7]
With the new IW4x update, all maps in which the Task Force 141 appears now feature a different icon compared to the original game.
Here are some screenshots of different maps:
![Favela](https://github.com/iw4x/iw4x-rawfiles/assets/154017747/2e00da1c-ee84-4b27-b9f2-4baa951d1352)
![Underpass](https://github.com/iw4x/iw4x-rawfiles/assets/154017747/4ae321bf-11c6-4946-9019-fb3e971de0ef)

**Comment by Rackover** [comment]
Fixed in 349be24b6ca125adc3205c6d63df44484b8b0529
